### ISSUE TITLE
Finding a quick way to open up LWT manager

### ISSUE THREAD

**Issue by paulri** [LouCypher/lwthemes#2]
I just installed your extension, and would like a convenient way of opening it. I have seen two methods so far: going into the Extensions list, hitting yours, and then click on Open. Also, I bookmarked the chrome page and put it on my bookmarks bar, but I’d like to get it off the bookmarks toolbar. Can I put a link to your extension in the Hamburger menu?

**Comment by LouCypher** [comment]
> Can I put a link to your extension in the Hamburger menu?

I'm planning to do so. Still learning [CustomizableUI](https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules/CustomizableUI.jsm).

**Comment by paulri** [comment]
OK thanks for the quick response. It is a bit handier than the default themes page.

**Comment by LouCypher** [comment]
There's a menuitem in Tools menu, though.

**Comment by LouCypher** [comment]
Closed via e6f3afa661
